# Yosep Kim

Question1: Backpropagation
In the following Neural Network, we have initialized the weights randomly. Use a training sample
(X,y) = ((1,1), 0) to update the weights (perform one round of backpropagation using one training
sample). Use learning rate parameter α = 0.1. Note that we have bias terms with value of 1 in
this network (no need for coding for this question).

In [39]:
from numpy import array, exp 
x1 = 1
x2 = 1
y = 0
a1 = (1*.8) + (-0.5 * x1) + (.4 * x2)
a1 = 1 / (1 + exp(-(a1)))
a2 = (-0.1 * x2) + (0.9 * x2) + (1 * x2)
a2 = 1 / (1 + exp(-(a2)))
a_one = (1 * .3) + (a1 * -1.2) + (a2*1.1)
a_one =  1 / (1 + exp(-(a_one)))
output = a_one
delta = (y - output) * output * (1 - output)
print("a1: " + str(a1))
print("a2: " + str(a2))
print("output: " + str(output))
print("delta: " + str(delta))

a1: 0.668187772168
a2: 0.8581489351
output: 0.60876847483
delta: -0.144990033885


In [40]:
delta_one = (-1.2*(delta))*a1*(1.0-a1)
delta_two = (1.1*(delta))*a2*(1.0-a2)
print("delta_one: " + str(delta_one))
print("delta_two: " + str(delta_two))

delta_one: 0.0385753884137
delta_two: -0.0194144952903


In [42]:
alpha = 0.1
weight_one_one = -1.2 + alpha * (delta)*  a1
weight_one_two = 1.1 + alpha * (delta)*  a2
weight_one_x1 = -0.5 + alpha * (delta_one) * 1
weight_two_x1 = 0.4 + alpha * (delta_one) * 1
weight_one_x2 = 0.9 + alpha * (delta_two) * 1
weight_two_x2 = 1.0 + alpha * (delta_two) * 1
print("weight_one_one: " + str(weight_one_one))
print("weight_one_two: " + str(weight_one_two))
print("weight_one_x1: " + str(weight_one_x1))
print("weight_two_x1: " + str(weight_two_x1))
print("weight_one_x2: " + str(weight_one_x2))
print("weight_two_x2: " + str(weight_two_x2))

weight_one_one: -1.20968805677
weight_one_two: 1.08755769568
weight_one_x1: -0.496142461159
weight_two_x1: 0.403857538841
weight_one_x2: 0.898058550471
weight_two_x2: 0.998058550471


# i don't know why i'm getting different numbers for accuracy when i have the same dataframe as my friends.  Although how i put that data in here is differently but after sorting the rows with my labels the dataframe looks the same as my friends. I entered in the right prediction codes and still get different accuracy.    

ANN Accuracy: 0.916666666667
Grid Best Accuracy Score: 0.961046188091
Grid Best Parameters: {'hidden_layer_sizes': (126,)}

Question2: Handwriting Recognition Using ANN:
Write and submit your python codes in “Jupyter Notebook” to perform the following tasks. Make
sure to provide proper descriptions as MarkDown for each section of your code.

a- Download the dataset “Digit” from CSNS. Check out the dataset. It includes 1797 small
images (8x8 pixels), each one includes a hand-written digit (0-9). You have to download
the corresponding csv file that includes the labels of the images. The goal is to build an
Artificial Neural Network that can recognize the hand-written digits.
Import the following two libraries to work with images:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

you can use:
mpimg.imread(file_name) to load an image, and
plt.imshow(image_name, cmap=plt.cm.gray_r, interpolation='nearest') to show an
image. Add %matplotlib inline at top of your code to make sure that the images will be
shown inside the Jupyter explorer page.

In [1]:
# Importing libraries and packages:

from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn import metrics
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:


# _0_jpg = matplotlib.image.imread('/home/cowboyuniverse/Workspace/_2018_Spring_CS5661/HW2/Digit/0.jpg')
# plt.imshow(_0_jpg, cmap=plt.cm.gray_r, interpolation='nearest')

b- Build the feature matrix and label vector: Each image is considered as a data sample with
pixels as features. Thus, to build the feature table you have to convert each 8x8 image
into a row of the feature matrix with 64 feature columns for 64 pixels

In [24]:
# "read_csv" is a pandas function to read csv files from web or local device:
import os
label = pd.read_csv('label.csv')
y_label = label['digit']
        
total_df = pd.DataFrame()
directory = 'Digit/'
row_order_list = []
for file in os.listdir(directory):
    if file.endswith(".jpg"):
        image_num = file.split(".")[0]
        jpg = mpimg.imread(directory+file)
        jpg_df = pd.DataFrame(jpg).transpose()
#         print(file.split(".")[0])
        row_order_list.append(int(file.split(".")[0]))
        col_df = pd.DataFrame()
        for num in range(0, len(jpg_df)):
            temp_df = pd.DataFrame()
            array = pd.Series(jpg_df[num])
            temp_df[str(image_num)] = array
            col_df = col_df.append(temp_df)
            if num > 7:
                break
        total_df = total_df.append(col_df.transpose())

x_df = total_df
x_df['index'] = row_order_list
sorted_row_df =x_df.sort_values(['index'], ascending=[True])
sorted_row_df = sorted_row_df.drop('index', axis=1)


In [25]:
sorted_row_df


0   1    2    3    4    5    6   7   0    1 ...    6   7   0   1    2  \
0      0   2   88  217  158   21    0   0  16    0 ...    4   0   4   3   87   
1      0   0   11  187  210   78    5   0  13    5 ...    0   0   0   0    0   
2      0   0    5   59  240  199    2   0   5    0 ...   92   0   0  11    0   
3      6   0  108  255  213   13   10   0   2  131 ...  168   1   0   0  118   
4      0   6    0   34  160    7    7   0   5    0 ...    7   0   0   0    2   
5     15   0  200  149    2    0   13   0   0   11 ...   69   0   7   0  143   
6      0  13    0  192  210    0   10   0   8    0 ...  134   3   0   0   11   
7     10   0  114  133  203  255  235  16   0   13 ...    0   0   1   0  225   
8      0   7  145  223  128   13    0   2   0    0 ...  133   0   0   3  169   
9      0   0  174  199    5    0    0   8  10   23 ...   90   1   0   3  145   
10     0  11    8  139  235  177    4   0   0    2 ...    0   0  19   0    9   
11     4   2    0    0  227  207   16   7   0    0 ...    4   0   0   0    0   
12     3   1   72  199   12    2    0   3   1   10 ...  130  19   1   0   62   
13     1  36  145  237  220  143   49   0   2   58 ...   90   5   6  11  203   
14     4   1    4  118  231   27    0   4   0    0 ...   10   0   0   0   12   
15     6  76  196  189  255  251   13  14   0  177 ...    0   0   8  60  237   
16     0   0    0  132  236   10    7   0  14    0 ...  255  29   0   5    0   
17     3   0   24  118  247  149    5   3   7   36 ...    0   0   0  11    0   
18     0   0  165  113  210  152    0   0   9    8 ...    5   0   7   0  174   
19     0  16   94  212   71    0    1   0   2    0 ...  255  43   0   1  115   
20     9   0   57  200  186  120    0   0   0   17 ...    0   0   6   0   21   
21     0  12    0   36  255  254   24   3   0    8 ...   33   0   0   0    5   
22     4   3  122  253   78    5    0  12   1   15 ...   65   0   6   0  113   
23     0  24  141  199  255  229   62   6   0   41 ...    5   6   0   4  235   
24     4   0   10    0  184   47    0   0   1    0 ...    8  11   0   0    0   
25     3   0  190  123  131  111    0   5   0   73 ...    2   5   6   0  169   
26     0   0   27  211  223   45    0   0   2    0 ...  190   0   0  19   38   
27     0   3    0  123  222  229   36   0   6    9 ...    0   9   0   0   27   
28     4   0  167  167   69    6    0   1   0    8 ...    8  13   0  14  114   
29     1   0  139  211  110    0    1   8   3    5 ...  255  21  11   0  123   
...   ..  ..  ...  ...  ...  ...  ...  ..  ..  ... ...  ...  ..  ..  ..  ...   
1767   0   0    7   24  255   27    0  13   8    0 ...    0  13   0   8    0   
1768   5   0   81  246  173    1    0   4   0    0 ...   75   2  11   0   64   
1769   0   4  143  178  234  108    0   5  15    0 ...   34   0   8   0  193   
1770   0  36  159  196  255  122    0   8   3   62 ...   87   0   0  33  217   
1771   0  16    0   94  190   94    7   0   6    0 ...  193   0   0   4    0   
1772   3   0   94  199  182  123    0   3   0   58 ...   12   0   0  10  115   
1773   0   6   27  197  167    0    0   3   6    8 ...  177   6   6   0   17   
1774   0   0   95  186  201   87    5   0   8    0 ...    0   6   0   2   32   
1775   4   0  105  255  251   35    6   0   0   25 ...    0  19   0   0  186   
1776   2   1  188  254  238  118    8   0   0   44 ...  113   0   0   0  157   
1777   5   0    4   36  212    0    6   0   0    6 ...    0   0   0  18    0   
1778   8   0   11   17  212  124    0   0   0    9 ...    0   0   0   3    0   
1779   0   1   55  160  245  255   50   7   0    0 ...    7   0   9   0   62   
1780   0  64  215  224  112    0    0   1   0  120 ...   92   3   0  73  239   
1781   7   0  165  253  227   68   19   0   0   25 ...   26   2   0  11  177   
1782   6   2  167  211   27    0   10   0   0  183 ...  192  14   1   8  145   
1783   0   9  227  214   27    7    0   6   6    0 ...  228   6   0   5  159   
1784   6   0   17  170  216  210    4   8   0    0 ...   45   0   0  16    0   
1785   

c- Use sklearn functions to split the dataset into testing and training sets with the following
parameters: test_size=0.1, random_state=2

In [30]:

X_train, X_test, y_train, y_test = train_test_split(sorted_row_df, y_label, test_size=0.1, random_state=2)

d- Design and Train an ANN with one hidden layer with 80 neurons to recognize the digits
based on the training dataset that you built in part (c). Use random_state=1,
learning_rate_init = 0.002. Then, Test your ANN on testing set (from part(c)), and
calculate and report the accuracy. Also, calculate and report the Confusion Matrix.

In [31]:
my_ANN = MLPClassifier(hidden_layer_sizes=(80,), activation= 'logistic', 
                       solver='adam', alpha=1e-5, random_state=1, 
                       learning_rate_init = 0.002)

my_ANN.fit(X_train, y_train)

MLPClassifier(activation='logistic', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(80,), learning_rate='constant',
       learning_rate_init=0.002, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [32]:
y_predict_ann = my_ANN.predict(X_test)
score_ann = accuracy_score(y_test, y_predict_ann)
print('ANN Accuracy: ' + str(score_ann))

ANN Accuracy: 0.916666666667


In [33]:
cm_ANN = metrics.confusion_matrix(y_test, y_predict_ann)
print("Confusion matrix:")
print(cm_ANN)

Confusion matrix:
[[13  0  0  0  1  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  1  1]
 [ 0  0 14  0  0  0  0  0  0  0]
 [ 0  0  0 21  0  0  0  1  0  0]
 [ 0  0  0  0 16  0  0  1  3  1]
 [ 0  0  0  0  0 16  0  0  0  0]
 [ 0  1  0  0  0  0 17  0  0  0]
 [ 0  0  0  0  0  0  0 17  1  0]
 [ 0  2  0  0  0  0  0  0 17  0]
 [ 0  0  0  0  0  1  0  0  1 14]]


In [37]:

from sklearn.model_selection import GridSearchCV

In [38]:
# Searching for the best number of neurons by using GridSearch

neuron_number = [(i,) for i in range(50,200)]

param_grid = dict(hidden_layer_sizes = neuron_number)

my_ANN = MLPClassifier(activation='logistic', solver='adam', alpha=1e-5, random_state=1, learning_rate_init = 0.002)

grid = GridSearchCV(my_ANN, param_grid, cv=10, scoring='accuracy')

grid.fit(sorted_row_df, y_label)

print('Grid Best Accuracy Score: ' + str(grid.best_score_))
print('Grid Best Parameters: ' + str(grid.best_params_))

Grid Best Accuracy Score: 0.961046188091
Grid Best Parameters: {'hidden_layer_sizes': (126,)}
